name: Ubuntu (x64)


on:
    workflow_dispatch


jobs:
  deneme1:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2
        - name: Install dependencies
          run: sudo sed -Ei 's/^# deb-src /deb-src /' /etc/apt/sources.list && sudo apt update && sudo apt-get build-dep libllvm
        - name: Configure
          run: ./configure
        - name: Build
          run: cmake -S llvm -B build -G Ninja
        - name: Install
          run: sudo make install
